RTI-2133 Part 3
Executioner34/nuxt2-blog pull request #2
Opened 2022-12-22 15:01 UTC by Executioner34

# Функциональные изменения

- Добавлена стандартная разметка для сайта
- Добавлен список постов на&nbsp;главной странице
- Добавлена страница детального просмотра поста
- Добавлена страница ошибки роута

# Технологические изменения

- В конфиге убран авто-импорт

https://track.ratio.digital/youtrack/issue/RTI-2133/Part-3

2023-01-11 11:40 UTC, Executioner34 commented on components/views/_post-page/CommentForm/index.vue
> +      class="post-page-component">
Исправил

2023-01-11 11:40 UTC, Executioner34 commented on components/views/_post-page/CommentForm/index.vue
> +      <h1>Добавить комментраий</h1>
Исправил

2023-01-11 11:40 UTC, Executioner34 commented on components/views/_post-page/CommentForm/index.vue
> +            this.isLoading = false;
Исправил

2023-01-11 11:42 UTC, Executioner34 commented on components/views/_post-page/TheComment/index.vue
> +      <span><i class="el-icon-time"></i> {{ currentDate }}</span>
В ElementUI иконки добавляются через тег <i> с соответствующим классом, поэтому не исправил. Вынес в глобальный компонент AppIcon

2023-01-11 11:44 UTC, Executioner34 commented on components/views/_post-page/TheComment/index.vue
> +  <el-card class="post-page-component comment">
Исправил название компонента

2023-01-11 11:44 UTC, Executioner34 commented on components/views/_post-page/TheComment/index.vue
> +      type: [String, Number],
Исправил

2023-01-11 11:48 UTC, Executioner34 commented on components/views/_post-page/TheComment/index.vue
> +    currentDate() {
Исправил

2023-01-11 11:48 UTC, Executioner34 commented on components/views/_post-page/index.vue
> +   <header class="post-header">
Исправил

2023-01-11 11:49 UTC, Executioner34 commented on components/views/_post-page/index.vue
> +       <TheComment
Исправил

2023-01-11 11:49 UTC, Executioner34 commented on components/views/index/ThePost/index.vue
> +    class="index-page-component post"
Исправил

2023-01-11 11:49 UTC, Executioner34 commented on components/views/index/ThePost/index.vue
> +      this.$router.push('/post/1');
Исправил

2023-01-11 11:50 UTC, Executioner34 commented on components/views/index/index.vue
> +  <el-row type="flex" justify="center">
Исправил

2023-01-11 11:50 UTC, Executioner34 commented on layouts/error.vue
> +      <h1 class="error-title">Ошибка 404</h1>
Исправил)

2023-01-12 04:18 UTC, Denis-Str requested changes

2023-01-12 04:18 UTC, Denis-Str commented on pages/post/_id.vue
> +    <div class="top">
лучше назвать класс heading

2023-01-12 04:18 UTC, Denis-Str commented on pages/post/_id.vue
> +    <div class="middle">
это content

2023-01-12 04:18 UTC, Denis-Str commented on pages/post/_id.vue
> +    <div class="bottom">
тут лишняя обвертка, вокруг компонента, если нужно повесить класс, то его можно повесить прям на the-form

2023-01-12 04:18 UTC, Denis-Str commented on pages/post/_id.vue
> +      <div
по семантике все что перебирается это список, если списко это ul > li

2023-01-12 04:18 UTC, Denis-Str commented on pages/post/_id.vue
> +      <div
в идеале это отдельный компонент

2023-01-12 04:18 UTC, Denis-Str commented on static/mock/posts.json
> +[
мок это отдельная директория

2023-01-12 04:18 UTC, Denis-Str commented on store/posts/index.js
> +  async getPost({}, id) {
тут как бы не айс, если ты сделал запрос, то лучше сохранить тогда уже данные в сторе, а в компоненте уже их получать из state стор

2023-01-12 04:18 UTC, Denis-Str commented on store/posts/index.js
> +  async getPost({}, id) {
на будущие, если тебе не нужен первый аргумент, а только второй то пиши так async getPost(_, id), у тебя не видно, но так не будет линтер ругатьс

2023-01-12 04:18 UTC, Denis-Str requested changes
можно еще чуток лучше :)

2023-01-12 09:40 UTC, Executioner34 commented on assets/scss/global.scss
> +h1 {
Исправил

2023-01-12 09:40 UTC, Executioner34 commented on components/common/TheForm/index.vue
> +      :class="isLogin ? 'login' : ''">
Исправил

2023-01-12 09:40 UTC, Executioner34 commented on pages/post/_id.vue
> +    <div class="top">
Исправил

2023-01-12 09:42 UTC, Executioner34 commented on pages/post/_id.vue
> +    <div class="middle">
Назвал text-content. Потому что контент в виде картинки уже есть сверху.

2023-01-12 09:42 UTC, Executioner34 commented on pages/post/_id.vue
> +    <div class="bottom">
Исправил

2023-01-12 09:42 UTC, Executioner34 commented on pages/post/_id.vue
> +      <div
Исправил. И в другом компоненте тоже)

2023-01-12 09:49 UTC, Executioner34 commented on store/posts/index.js
> +  async getPost({}, id) {
Исправил)

2023-01-13 03:54 UTC, Denis-Str requested changes
по моку решение  в ютреке

2023-01-13 03:54 UTC, Denis-Str commented on static/mock/posts.json
> +[
решение в скинкл в ютрек, у меня работает - мок вынесен из статика

2023-01-13 07:26 UTC, Executioner34 commented on static/mock/posts.json
> +[
Я смотрел в сторону использования axios и без импорта) Думал что так нужно

2023-01-13 08:25 UTC, Denis-Str approved these changes

2023-01-13 08:25 UTC, merged